export const SET_CONFIG = 'SET_CONFIG';
export const UPDATE_CONFIG = 'UPDATE_CONFIG';

export const FETCH_TOP_MANGA_REQUEST = 'FETCH_TOP_MANGA_REQUEST';
export const FETCH_TOP_MANGA_SUCCESS = 'FETCH_TOP_MANGA_SUCCESS';
export const FETCH_TOP_MANGA_FAILURE = 'FETCH_TOP_MANGA_FAILURE';
export const FETCH_FOLLOW_MANGA_REQUEST = 'FETCH_FOLLOW_MANGA_REQUEST';
export const FETCH_FOLLOW_MANGA_SUCCESS = 'FETCH_FOLLOW_MANGA_SUCCESS';
export const FETCH_FOLLOW_MANGA_FAILURE = 'FETCH_FOLLOW_MANGA_FAILURE';
export const FETCH_READED_MANGA_REQUEST = 'FETCH_READED_MANGA_REQUEST';
export const FETCH_READED_MANGA_SUCCESS = 'FETCH_READED_MANGA_SUCCESS';
export const FETCH_READED_MANGA_FAILURE = 'FETCH_READED_MANGA_FAILURE';
export const FETCH_AUTO_COMPLETE_REQUEST = 'FETCH_AUTO_COMPLETE_REQUEST';
export const FETCH_AUTO_COMPLETE_SUCCESS = 'FETCH_AUTO_COMPLETE_SUCCESS';
export const FETCH_AUTO_COMPLETE_FAILURE = 'FETCH_AUTO_COMPLETE_FAILURE';
export const ADD_READED = 'ADD_READED';

export const SYNC_WITH_LOCALSTORAGE = 'SYNC_WITH_LOCALSTORAGE';
export const SET_LOCAL_NAME = 'SET_LOCAL_NAME';
export const SET_LOCAL_EMAIL = 'SET_LOCAL_EMAIL';
