export const countryType = {
	jp: { title: 'Manga', slug: 'nhat-ban'},
	cn: { title: 'Manhua', slug: 'trung-quoc'},
	kr: { title: 'Manhwa', slug: 'han-quoc'},
}

export const suggestPlaceholder = [
  'One Piece',
  'Kimetsu No Yaiba',
  'Onepunch Man',
  'The Beginning After The End',
  'Bách Luyện Thành Thần',
  'Toàn Chức Pháp Sư',
  'Attack On Titan',
  'Fairy Tail',
  'My Hero Academia',
  'Kanojo, Okarishimasu',
  'Tối Cường Phản Sáo Lộ Hệ Thống',
  'Yakusoku No Neverland',
  'The Gamer',
  'Anh Hùng ? Ta Không Làm Lâu Rồi',
  'Bokutachi Wa Benkyou Ga Dekinai',
  'Tonikaku Kawaii',
  'Kaguya-sama: Love Is War ',
  'Đấu La Đại Lục',
  'Kingdom',
  'Fff-Class Trashero',
  'Kage No Jitsuryokusha Ni Naritakute!',
  'The Legendary Moonlight Sculptor',
  'Tomodachi Game',
  'Huyết Ma Nhân',
  'Darwins Game',
  'Shokugeki No Soma',
];
